http:
  port: 8765

pop3:
  username: liyubei
  password: password
  host: email.baidu.com
  port: 995
  tls: true
  interval: 60

smtp:
  username: internal\liyubei
  password: password
  host: email.baidu.com
  port: 25
  tls: true

frontend:
  from: username@baidu.com
  name: username
