pop3:
  username: liyubei
  password: password
  hostname: email.baidu.com:995
  tls: true
  interval: 60

smtp:
  username: internal\liyubei
  password: password
  hostname: email.baidu.com:25
  tls: true

dirs:
  base: data/baidu.com/liyubei
